import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from './../components/banner';
import Card from './../components/card';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleBannerButtonClick = () =>{
    console.log("Hello Banner Buttoon");
  }
  return (
    <>
      <Head>
        <title>Discover Your Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Banner buttonText = "View Nearby Shops" handleOnClick = {handleBannerButtonClick} ></Banner>
      <div className={styles.heroImage}>
      <Image alt="hero image" src ="/static/hero-image.png" width={700} height={400}></Image>;
      </div>
      <div className={styles.cardLayout}>
        <Card className={styles.card} name="Black Friday" target="/coffee-store/black-friday-shop" />
        <Card className={styles.card} name="Black Friday" target="/coffee-store/black-friday-shop" />
        <Card className={styles.card} name="Black Friday" target="/coffee-store/black-friday-shop" />
      </div>
      </main>
      <footer className={styles.footer}></footer>
    </>
  )
}
