import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from './../components/banner';
import Card from './../components/card';
import coffeeStores from '../data/coffee-stores.json';
const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(context) {
  return {
    props: {coffeeStores},
  }
}
export default function Home(props) {
  const handleBannerButtonClick = () =>{
    console.log("Hello Banner Buttoon");
  }
  const coffeeStoresList = props.coffeeStores;
  return (
    <>
      <Head>
        <title>Discover Your Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Banner buttonText = "View Nearby Shops" handleOnClick = {handleBannerButtonClick} ></Banner>
      <div className={styles.heroImage}>
      <Image alt="hero image" src ="/static/hero-image.png" width={700} height={400}></Image>;
      </div>
      {coffeeStoresList.length > 0 && 
      <>
      <h2 className={styles.heading2}>Toronto Stores</h2>
              <div className={styles.cardLayout}>
{      coffeeStoresList.map((coffeStore)=>{
        return <Card key={coffeStore.id} className={styles.card} name={coffeStore.name} imageUrl={coffeStore.imgUrl} target={`/coffee-store/${coffeStore.id}`} /> 
      })
}        
      </div>
      </>
      }


      </main>
      <footer className={styles.footer}></footer>
    </>
  )
}
